default_settings: null
behaviors:
  Quadcopter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 32768
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 4
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 5000000
    max_steps: 150000000
    time_horizon: 500
    summary_freq: 250000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: TrainingExecutable
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: RLHover
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
