behaviors:
  Quadcopter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 32768
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.3
      lambd: 0.9
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 500
    summary_freq: 250000
